# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0e27fe413a7fa7ae36f713d307d36d674095c57d16c7128d391fcd533205b6fe9828185c1c88c5ffd2656b5f0ced5e24b8ae2875e02ad4c21ce0c8325aba142
  user_password: 'user'
  admin_password: 'admin'

test:
  secret_key_base: 90aedec214fe03e758c795f3b2f18be5542fd093457691629aedf0fe0f37de064571d1149ecc0c5cfa13b4b51f9240ec6ba1c5075770be18e4fb08e361e9c0cb
  user_password: 'user'
  admin_password: 'admin'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  user_password: <%= ENV["USER_PASSWORD"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
